% This test file was generated by Copilot. Validate generated output before use.
classdef TestSimulationModel < matlab.unittest.TestCase
    % Unit tests for SimulationModel class.
    %
    % These tests assume that a MAT-file 'simFunction_Dose.mat' exists on the
    % MATLAB path and contains variables 'simFun' and 'doseTable' compatible
    % with SimulationModel constructor expectations.

    properties
        Model % instance of SimulationModel
    end

    methods(TestMethodSetup)
        function createModel(testCase)
            % Create a fresh instance for each test.
            testCase.Model = SimulationModel();
        end
    end

    methods(Test)
        function testConstructorInitializesProperties(testCase)
            % Verify constructor sets up essential properties and original values.
            m = testCase.Model;

            % SimFun and DoseTable should be non-empty
            testCase.verifyNotEmpty(m.SimFun, 'SimFun should be loaded by constructor.');
            testCase.verifyNotEmpty(m.DoseTable, 'DoseTable should be loaded by constructor.');

            % Original parameter values should be numeric scalars
            testCase.verifyGreaterThan(m.Kel0, 0);
            testCase.verifyGreaterThan(m.Kon0, 0);
            testCase.verifyGreaterThan(m.Kdeg0, 0);
            testCase.verifyGreaterThan(m.Duration0, 0);
            testCase.verifyGreaterThan(m.Interval0, 0);
            testCase.verifyGreaterThan(m.Amount0, 0);
        end

        function testSimulateProducesSimDataAndTable(testCase)
            % Calling simulate with default parameters should populate SimData and SimDataTable.
            m = testCase.Model;

            % Ensure no SimData before simulation
            if ~isempty(m.SimDataTable)
                % reset by creating a new instance if leftover data exists
                m = SimulationModel();
                testCase.Model = m;
            end

            % Run simulation with default parameters
            m.simulate();

            % SimData and SimDataTable should be set
            testCase.verifyNotEmpty(m.SimData, 'SimData should be set after simulate.');
            testCase.verifyNotEmpty(m.SimDataTable, 'SimDataTable should be set after simulate.');

            % SimDataTable must contain Time and RO variables
            testCase.verifyTrue(ismember('Time', m.SimDataTable.Properties.VariableNames), ...
                'SimDataTable must contain Time column.');
            testCase.verifyTrue(ismember('RO', m.SimDataTable.Properties.VariableNames), ...
                'SimDataTable must contain RO column produced by simFun.');

            % Dose column should exist and have NaNs except dosing times
            testCase.verifyTrue(ismember('Dose', m.SimDataTable.Properties.VariableNames), ...
                'SimDataTable must contain Dose column.');
            doseCol = m.SimDataTable.Dose;
            testCase.verifySize(doseCol, [height(m.SimDataTable), 1]);
        end

        function testSimulateAppliesCustomParameters(testCase)
            % Verify simulate updates DoseTable.Amount and Interval when custom parameters provided.
            m = testCase.Model;

            originalAmount = m.DoseTable.Amount;
            originalInterval = m.DoseTable.Interval;

            % choose positive custom parameters: [kel, kon, kdeg, duration, amount, interval]
            customParams = [m.Kel0, m.Kon0, m.Kdeg0, m.Duration0, originalAmount*2, max(1, originalInterval)];

            m.simulate(customParams);

            testCase.verifyEqual(m.DoseTable.Amount, customParams(5), 'Dose amount should be updated.');
            testCase.verifyEqual(m.DoseTable.Interval, customParams(6), 'Dose interval should be updated.');

            % SimDataTable should reflect dosing times consistent with the provided interval
            dosingTimes = customParams(6)*(0:customParams(4)/customParams(6));
            % At least one dosing time should be present in Time column
            hasDosing = any(ismember(m.SimDataTable.Time, dosingTimes));
            testCase.verifyTrue(hasDosing, 'SimDataTable.Time should include dosing times for given interval.');
        end

        function testROIsBetweenThresholdsLogical(testCase)
            % simulate then verify ROIsBetweenThresholds returns logical scalar.
            m = testCase.Model;
            m.simulate();

            val = m.ROIsBetweenThresholds;
            testCase.verifyClass(val, 'logical');
            testCase.verifySize(val, [1,1]);
        end

        function testSimulateWithInvalidParametersRaises(testCase)
            % Passing invalid (non-positive) parameters should trigger argument validation.
            m = testCase.Model;

            % Create invalid parameters with a non-positive entry
            invalidParams = [m.Kel0, m.Kon0, -1*m.Kdeg0, m.Duration0, m.Amount0, m.Interval0];

            testCase.verifyError(@() m.simulate(invalidParams), 'MATLAB:validators:mustBePositive');
        end
    end
end